include 'System\Display\Display.h.asm'

Game.UI.View.SYMBOL_CLEAR = ' '
Game.UI.View.SELECTOR_SYMBOL = '>'
Game.UI.View.SELECTOR_COLOR = 11

Game.UI.View.GAME_MODE_SELECT_SCREEN_TITLE_COLOR = 15
Game.UI.View.GAME_MODE_SELECT_SCREEN_TITLE_ROW = 6
Game.UI.View.GAME_MODE_SELECT_SCREEN_TITLE_COLUMN = 15
Game.UI.View.GAME_MODE_SELECT_SCREEN_MODE_1_COLOR = 44
Game.UI.View.GAME_MODE_SELECT_SCREEN_MODE_1_ROW = 11
Game.UI.View.GAME_MODE_SELECT_SCREEN_MODE_1_COLUMN = 16
Game.UI.View.GAME_MODE_SELECT_SCREEN_MODE_1_SELECTOR_COLUMN = 14
Game.UI.View.GAME_MODE_SELECT_SCREEN_MODE_2_COLOR = 42
Game.UI.View.GAME_MODE_SELECT_SCREEN_MODE_2_ROW = 13
Game.UI.View.GAME_MODE_SELECT_SCREEN_MODE_2_COLUMN = 16
Game.UI.View.GAME_MODE_SELECT_SCREEN_MODE_2_SELECTOR_COLUMN = 14

Game.UI.View.GAME_COMPLEXITY_SELECT_SCREEN_TITLE_COLOR = 15
Game.UI.View.GAME_COMPLEXITY_SELECT_SCREEN_TITLE_ROW = 6
Game.UI.View.GAME_COMPLEXITY_SELECT_SCREEN_TITLE_COLUMN = 15
Game.UI.View.GAME_COMPLEXITY_SELECT_SCREEN_COMPLEXITY_1_COLOR = 10
Game.UI.View.GAME_COMPLEXITY_SELECT_SCREEN_COMPLEXITY_1_ROW = 10
Game.UI.View.GAME_COMPLEXITY_SELECT_SCREEN_COMPLEXITY_1_COLUMN = 18
Game.UI.View.GAME_COMPLEXITY_SELECT_SCREEN_COMPLEXITY_1_SELECTOR_COLUMN = 15
Game.UI.View.GAME_COMPLEXITY_SELECT_SCREEN_COMPLEXITY_2_COLOR = 44
Game.UI.View.GAME_COMPLEXITY_SELECT_SCREEN_COMPLEXITY_2_ROW = 12
Game.UI.View.GAME_COMPLEXITY_SELECT_SCREEN_COMPLEXITY_2_COLUMN = 17
Game.UI.View.GAME_COMPLEXITY_SELECT_SCREEN_COMPLEXITY_2_SELECTOR_COLUMN = 15
Game.UI.View.GAME_COMPLEXITY_SELECT_SCREEN_COMPLEXITY_3_COLOR = 40
Game.UI.View.GAME_COMPLEXITY_SELECT_SCREEN_COMPLEXITY_3_ROW = 14
Game.UI.View.GAME_COMPLEXITY_SELECT_SCREEN_COMPLEXITY_3_COLUMN = 18
Game.UI.View.GAME_COMPLEXITY_SELECT_SCREEN_COMPLEXITY_3_SELECTOR_COLUMN = 15

Game.UI.View.GAME_EXIT_CONFIRMATION_SCREEN_TITLE_COLOR = 15
Game.UI.View.GAME_EXIT_CONFIRMATION_SCREEN_TITLE_ROW = 10
Game.UI.View.GAME_EXIT_CONFIRMATION_SCREEN_TITLE_COLUMN = 15
Game.UI.View.GAME_EXIT_CONFIRMATION_SCREEN_OPTION_1_COLOR = 10
Game.UI.View.GAME_EXIT_CONFIRMATION_SCREEN_OPTION_1_ROW = 12
Game.UI.View.GAME_EXIT_CONFIRMATION_SCREEN_OPTION_1_COLUMN = 19
Game.UI.View.GAME_EXIT_CONFIRMATION_SCREEN_OPTION_1_SELECTOR_COLUMN = 17
Game.UI.View.GAME_EXIT_CONFIRMATION_SCREEN_OPTION_2_COLOR = 40
Game.UI.View.GAME_EXIT_CONFIRMATION_SCREEN_OPTION_2_ROW = 14
Game.UI.View.GAME_EXIT_CONFIRMATION_SCREEN_OPTION_2_COLUMN = 19
Game.UI.View.GAME_EXIT_CONFIRMATION_SCREEN_OPTION_2_SELECTOR_COLUMN = 17

Game.UI.View.GAME_SCREEN_PLAYER_1_TURN_MARKER = '<'
Game.UI.View.GAME_SCREEN_PLAYER_2_TURN_MARKER = '>'
Game.UI.View.GAME_SCREEN_SCORE_DELIMITER_SYMBOL = ':'
Game.UI.View.GAME_SCREEN_TURN_MARKER_COLOR = 11
Game.UI.View.GAME_SCREEN_STICK_HEIGHT = 50
Game.UI.View.GAME_SCREEN_STICK_WIDTH = 4
Game.UI.View.GAME_SCREEN_STICKS_GAP = Game.UI.View.GAME_SCREEN_STICK_WIDTH * 2
Game.UI.View.GAME_SCREEN_STICKS_COLOR_COMPLEXITY_1 = 10
Game.UI.View.GAME_SCREEN_STICKS_COLOR_COMPLEXITY_2 = 44
Game.UI.View.GAME_SCREEN_STICKS_COLOR_COMPLEXITY_3 = 40
Game.UI.View.GAME_SCREEN_STICKS_COLOR_TWO_PLAYERS = 42
Game.UI.View.GAME_SCREEN_SCORE_DIGITS_AMOUNT = 3
Game.UI.View.GAME_SCREEN_SCORE_ROW = 6
Game.UI.View.GAME_SCREEN_SCORE_ROW_COLOR = 43
Game.UI.View.GAME_SCREEN_PLAYER_1_SCORE_COLUMN = 15
Game.UI.View.GAME_SCREEN_PLAYER_2_SCORE_COLUMN = 22
Game.UI.View.GAME_SCREEN_SCORE_DELIMITER_COLUMN = 19
Game.UI.View.GAME_SCREEN_PLAYER_1_NAME_COLUMN = 6
Game.UI.View.GAME_SCREEN_PLAYER_2_NAME_COLUMN = 26
Game.UI.View.GAME_SCREEN_PLAYER_1_TURN_MARKER_COLUMN = 18
Game.UI.View.GAME_SCREEN_PLAYER_2_TURN_MARKER_COLUMN = 21

Game.UI.View.ROUND_RESULT_SCREEN_WINNER_ROW = 12
Game.UI.View.ROUND_RESULT_SCREEN_WINNER_COLUMN = 13
Game.UI.View.ROUND_RESULT_SCREEN_MODE_1_PLAYER_1_WINNER_COLOR = 10
Game.UI.View.ROUND_RESULT_SCREEN_MODE_1_PLAYER_2_WINNER_COLOR = 40
Game.UI.View.ROUND_RESULT_SCREEN_MODE_2_PLAYER_1_WINNER_COLOR = 44
Game.UI.View.ROUND_RESULT_SCREEN_MODE_2_PLAYER_2_WINNER_COLOR = 44
