include 'Utils\Random\Random.h.asm'

Game.Logic.MAX_PROBABILITY = 100

Game.Logic.MIN_STICKS_COUNT = 15
Game.Logic.MAX_STICKS_COUNT = 25

Game.Logic.COMPLEXITY_1_PLAYER_1_STARTS_ROUND_PROBABILITY = 70
Game.Logic.COMPLEXITY_2_PLAYER_1_STARTS_ROUND_PROBABILITY = 50
Game.Logic.COMPLEXITY_3_PLAYER_1_STARTS_ROUND_PROBABILITY = 20
Game.Logic.COMPLEXITY_NONE_PLAYER_1_START_ROUND_PROBABILITY = 50

Game.Logic.COMPLEXITY_1_COMPUTER_MAKES_CORRECT_MOVE_PROBABILITY = 50
Game.Logic.COMPLEXITY_2_COMPUTER_MAKES_CORRECT_MOVE_PROBABILITY = 80
Game.Logic.COMPLEXITY_3_COMPUTER_MAKES_CORRECT_MOVE_PROBABILITY = 90
Game.Logic.COMPLEXITY_NONE_COMPUTER_MAKES_CORRECT_MOVE_PROBABILITY = 0
