Display.VIDEO_MODE_GRAPHIC_13 = 0x13
Display.VIDEO_MODE_GRAPHIC_13_WIDTH_PIXELS = 320
Display.VIDEO_MODE_GRAPHIC_13_HEIGHT_PIXELS = 200
Display.VIDEO_MODE_GRAPHIC_13_WIDTH_SYMBOLS = 40
Display.VIDEO_MODE_GRAPHIC_13_HEIGHT_SYMBOLS = 25
Display.VIDEO_MODE_GRAPHIC_13_MEMORY_SEGMENT = 0xA000

Display.COLOR_CLEAR = 0

Display.SYMBOL_MINUS = '-'
Display.SYMBOL_ZERO = '0'
