include 'System\Display\Display.h.asm'

Game.UI.View.SYMBOL_CLEAR = ' '
Game.UI.View.SELECTOR_SYMBOL = '>'
Game.UI.View.SELECTOR_COLOR = 11

Game.UI.View.GAME_MODE_SELECT_SCREEN_TITLE_COLOR = 15
Game.UI.View.GAME_MODE_SELECT_SCREEN_TITLE_ROW = 10
Game.UI.View.GAME_MODE_SELECT_SCREEN_TITLE_COLUMN = 15
Game.UI.View.GAME_MODE_SELECT_SCREEN_MODE_1_COLOR = 44
Game.UI.View.GAME_MODE_SELECT_SCREEN_MODE_1_ROW = 12
Game.UI.View.GAME_MODE_SELECT_SCREEN_MODE_1_COLUMN = 16
Game.UI.View.GAME_MODE_SELECT_SCREEN_MODE_1_SELECTOR_COLUMN = 14
Game.UI.View.GAME_MODE_SELECT_SCREEN_MODE_2_COLOR = 42
Game.UI.View.GAME_MODE_SELECT_SCREEN_MODE_2_ROW = 14
Game.UI.View.GAME_MODE_SELECT_SCREEN_MODE_2_COLUMN = 16
Game.UI.View.GAME_MODE_SELECT_SCREEN_MODE_2_SELECTOR_COLUMN = 14

Game.UI.View.GAME_SCREEN_STICK_HEIGHT = 50
Game.UI.View.GAME_SCREEN_STICK_WIDTH = 4
Game.UI.View.GAME_SCREEN_STICKS_GAP = Game.UI.View.GAME_SCREEN_STICK_WIDTH * 2
Game.UI.View.GAME_SCREEN_STICKS_COLOR_EASY_LEVEL = 10
Game.UI.View.GAME_SCREEN_STICKS_COLOR_MEDIUM_LEVEL = 44
Game.UI.View.GAME_SCREEN_STICKS_COLOR_HARD_LEVEL = 40
Game.UI.View.GAME_SCREEN_STICKS_COLOR_TWO_PLAYERS = 42
